[package]
name = "network-tester"
version = "0.1.0"
authors = ["Guy Garcia <guysebastiangarcia@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[workspace]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
default = []

[dependencies]
colored = "2.0.0"
shade-protocol = { version = "0.1.0", path = "../shade_protocol" }
secretcli = { version = "0.1.0", path = "../secretcli" }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.67"}
rand = { version = "0.8.4" }
cosmwasm-std = { git = "https://github.com/enigmampc/SecretNetwork", tag = "v1.0.4-debug-print" }

[[bin]]
name = "test"
path = "src/run.rs"

[[bin]]
name = "governance"
path = "src/governance.rs"